### ISSUE TITLE
"assign null to have no file written to" does not seem to function as described

### ISSUE THREAD

**Issue by notmessenger** [GochoMugo/json-concat#1]
That is a bullet point describing the "dest" option.

Due to the setting of "dest" to "./concat.json" on https://github.com/GochoMugo/json-concat/blob/master/dist/json-concat.js#L58 checks such as https://github.com/GochoMugo/json-concat/blob/master/dist/json-concat.js#L64 never allow for null to be a value that will exist on this property.

**Comment by GochoMugo** [comment]
Solved in [v0.0.0](https://github.com/GochoMugo/json-concat/releases/tag/v0.0.0). Please note that this is the first stable release. Some minor change to the API.

Thanks for the keen eyes :eyes:
