### ISSUE TITLE
Returning only the last file content

### ISSUE THREAD

**Issue by coluccini** [GochoMugo/json-concat#3]
Hi,
I'm doing a simple implementation (a copy/paste from the readme example) to merge the json from a few files inside a directory, but I'm just getting the content of the last file on that directory.
The code is:

```
const jsonConcat = require('json-concat');

jsonConcat({
  src: 'translations/json',
  dest: 'translations/fullUsedMessages.json',
}, (error, json) => {
  if (error) {
    throw error;
  }
  console.log(json);
});
```

and the translations/json folder structure is:

```
- translations
-- json
--- a.json
--- b.json
--- c.json
```

I'm getting just c.json content (and if i remove c.json I get b.json content). 
Is there an config I'm missing out?
Thanks!

**Comment by coluccini** [comment]
Sorry, it was something related a duplicate ids on the jsons.

**Comment by GochoMugo** [comment]
Thanks @coluccini for using this library. :+1:
